Use python 3.11 on readthedocs build
Despite python 3.12 being used by the readthedocs example, it leads to a
build failure due to a known issue with pip on Ubuntu 22.04 with Python
3.12 which manifests as:

AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Use python 3.11 instead which should work.